run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - bodyclose
    - noctx
    - gosec
    - copyloopvar
    - misspell

linters-settings:
  gofmt:
    simplify: true

  gosec:
    excludes:
      - G404 # Allow weak random number generator for non-crypto use

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
